/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Test2 } from "../Test2";

export class Test2__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Test2> {
    return super.deploy(overrides || {}) as Promise<Test2>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Test2 {
    return super.attach(address) as Test2;
  }
  connect(signer: Signer): Test2__factory {
    return super.connect(signer) as Test2__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Test2 {
    return new Contract(address, _abi, signerOrProvider) as Test2;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "base",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600a60146040516100219061006e565b61002c92919061007a565b604051809103906000f080158015610048573d6000803e3d6000fd5b50600080546001600160a01b0319166001600160a01b0392909216919091179055610088565b60df8061015083390190565b918252602082015260400190565b60ba806100966000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80635001f3b514602d575b600080fd5b60336047565b604051603e91906063565b60405180910390f35b60005473ffffffffffffffffffffffffffffffffffffffff1681565b73ffffffffffffffffffffffffffffffffffffffff9190911681526020019056fea26469706673582212201f138180ca81aef8b44fd66e2f57c651d91355412011ec2b93953213047f7bd664736f6c63430006080033608060405234801561001057600080fd5b506040516100df3803806100df83398101604081905261002f91610036565b5050610059565b60008060408385031215610048578182fd5b505080516020909101519092909150565b6078806100676000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80638129fc1c14602d575b600080fd5b60336035565b005b61205a603f600081565b5056fea26469706673582212203ec6efa83defbe5dcd1cccf00b65909c02967dd9c1eebdc6fec0d821ea7a37e064736f6c63430006080033";
