/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Test } from "./Test";
export type { Test2 } from "./Test2";

export { Test__factory } from "./factories/Test__factory";
export { Test2__factory } from "./factories/Test2__factory";
